bbc/tams

.github/workflows/commit-check-workflow.yml

Add commit check workflow
Story URL: https://www.pivotaltracker.com/story/show/186692281

Add commit check workflow

---

README.md

Story URL: https://www.pivotaltracker.com/story/show/186644488

Add API Versioning section to README

---

api/TimeAddressableMediaStore.yaml

Starting at 2.0 rather than 1.0 to allow it to be aligned with the internal implementation.
Story URL: https://www.pivotaltracker.com/story/show/186644490

Bump version to 2.0

---

docs/adr/decisions/0000-use-markdown-adrs-to-record-design-decisions.md
docs/adr/decisions/README.md
docs/adr/template/adr-template.md

Add folder structure to support use of Architectural (Any) Decision Records
Add MADR template and apply slight modifications to simplify for our use
Create an initial ADR doc from the template to document the decision to use (M)ADRs
Story URL: https://www.pivotaltracker.com/story/show/186644493

Add ADR folder structure, templates and initial ADR doc

---

.github/CODEOWNERS
.github/pull_request_template.md

Adds rd-cloudfit-apmm team as a reviewer on PRs automatically.
Story URL: https://www.pivotaltracker.com/n/projects/2147543/stories/186868288

Add .github codeowners file

---

README.md

Reduce use of the term 'segment' in favor of Flow Segment.
Story URL: https://www.pivotaltracker.com/n/projects/2147543/stories/186876593

Clarify Flow Segment in README

---

docs/adr/decisions/0004-ancestry-relationships.md
docs/adr/decisions/xxxx-ancestry-relationships.md

This PR adds an ADR for defining ancestry relationships. It is a draft for discussion and comments are welcome.
Story URL: https://www.pivotaltracker.com/story/show/186711208

adr: ancestry relationships

---

docs/adr/decisions/0006-flow-status.md
docs/adr/decisions/xxxx-flow-status.md

This PR is started in draft status to allow feedback before proposing an approach. 
Story URL: https://www.pivotaltracker.com/story/show/186711250

adr: Add a Flow update status ADR

---

README.md

Story URL: https://www.pivotaltracker.com/story/show/187209886

README: Add references to Timestamp and TimeRange string patterns

---

api/TimeAddressableMediaStore.yaml
docs/adr/decisions/0010-pagination-of-listing-endpoints.md

- Adds query parameters and headers for paging through the Flow and Source listing endpoints.
- Also adds an ADR describing which approach was taken
Story URL: https://www.pivotaltracker.com/story/show/187019592
N/A

Add pagination of listing endpoints

---

docs/adr/decisions/0011-random-storage-object-ids.md

Oops, forgot to update the ADR status before merging.
Story URL:

adr: Update random-storage-object-ids ADR status to accepted

---

README.md
api/TimeAddressableMediaStore.yaml
api/schemas/flow-segment.json
docs/adr/decisions/0013-timeline-exposed-by-flows.md

- Adds ADR considering which timeline the Flow timeline refers to when temporal re-ordering is used
- Updates API specification and README with some clarifying wording
- Also indicates that segments should contain complete GOPs
Story URL: https://www.pivotaltracker.com/story/show/187247728
Merge after #34 

Clarify that flow timeline is presentation timeline

---

docs/appnotes/README.md
docs/appnotes/template/appnote-template.md

Adds a simple template & structure for Application Notes
Story URL: https://www.pivotaltracker.com/story/show/186961743

Basic Application Notes

---

api/schemas/collection-item.json
api/schemas/flow-audio.json
api/schemas/flow-data.json
api/schemas/flow-video.json

Improve descriptions of flow parameters 
Story URL: https://www.pivotaltracker.com/story/show/185727931

Improve descriptions of flow parameters 

---

api/schemas/flow-video.json

Minor tweak to pixel_aspect_ratio description based on feedback from @himslm01 
Story URL: https://www.pivotaltracker.com/story/show/185727931

Minor tweak to pixel_aspect_ratio description based on feedback

---

docs/adr/0012-add-flow-collections.md
docs/adr/0013-timeline-exposed-by-flows.md
docs/adr/0014-add-event-stream.md

Some of the ADR documents were left in the `proposed` state when they were `accepted`.
Story URL: https://www.pivotaltracker.com/story/show/187506602

adr: Fix status of ADRs that were accepted

---

api/TimeAddressableMediaStore.yaml
docs/adr/0002-add-sources-to-api.md
docs/adr/0018-restrict-direct-source-modification.md

Adds an ADR concerning direct creation, modification, and deletion of Sources
Story URLs:
* https://www.pivotaltracker.com/story/show/187294356
* https://www.pivotaltracker.com/story/show/187315678

ADR: Restrict direct Source modification

---

docs/appnotes/0004-tams-for-data.md

Add app note regarding using tams for data
Story URL: https://www.pivotaltracker.com/story/show/187412251

Add app note regarding using tams for data

---

docs/appnotes/0002-Timing-in-MPEG-TS.md

Adds AN-0002: Timing in MPEG-TS
Story URL: https://www.pivotaltracker.com/story/show/187412238

AN-0002 First Draft

---

api/examples/flow-get-200-audio-aac.json
api/examples/flow-get-200-video-h264.json
api/examples/flow-get-200-video-raw.json
api/examples/flow-put-201.json
api/examples/flow-put.json
api/examples/flow-tags-get-200.json
api/examples/flows-get-200.json
docs/appnotes/0003-tag-names.md

Add app note regarding tag names
Story URL: https://www.pivotaltracker.com/story/show/187412243

Add app note regarding tag names

---

.github/workflows/ci-workflow.yml

We currently only upload renders of the API Specification as it exists on `main`. This adds functionality to upload the spec as it is on `main` and all releases.
Story URL: https://www.pivotaltracker.com/story/show/187576124

Upload multiple API version renders

---

README.md
api/examples/service-get-200.json

Update documentation links following change to endpoints introduced in https://github.com/bbc/tams/pull/55
Story URL: https://www.pivotaltracker.com/story/show/187576124

Update documentation links to use new versioned documentation URLs

---

docs/adr/0016-checksums-and-filesize.md

Add ADR for checksum and filesize metadata
Story URL: https://www.pivotaltracker.com/story/show/187060666

Add ADR for checksum and filesize metadata

---

api/TimeAddressableMediaStore.yaml

Fixes a typo referring to a "Flow Deletion Request" which should say "Flow Delete Request"
Story URL:

Replace "Flow Deletion Request" in description with "Flow Delete Request"

---

api/TimeAddressableMediaStore.yaml

Fix typo in fix to typo
Story URL:

Fix typo in fix to typo

---

api/TimeAddressableMediaStore.yaml
docs/adr/0005-flow-read-write-permissions.md

Add missing 403 responses related to ADR-0005 "Flow Read-Write Permissions"
Story URL: https://www.pivotaltracker.com/story/show/187554185
Original PR which added read-only functionality https://github.com/bbc/tams/pull/24

Add missing 403 responses related to ADR-0005

---

docs/appnotes/0006-containers-and-mappings.md

Add a note on API version compatibility to App Note 0006
Story URL:

Add a note on API version compatibility to App Note 0006

---

api/schemas/flow-core.json
api/schemas/source.json
docs/adr/0019-consolidate-modified-updated-terms.md

Add ADR and proposed implementation to rename "modified_by" properties in core Source and Flow schemas to "updated_by"
Story URL: https://www.pivotaltracker.com/story/show/187609408
N/A

Rename "modified_by" properties to "updated_by" in Source and Flow schemas

---

api/examples/flow-get-200-audio-aac-multi.json
api/examples/flow-get-200-audio-aac.json
api/examples/flow-get-200-video-h264.json
api/examples/flow-get-200-video-raw.json
api/examples/flows-get-200.json
api/examples/source-get-200-basic.json
api/examples/source-get-200-multi.json
api/examples/sources-get-200.json

This PR applies the changes from #60 to the JSON examples.
Story URL: https://www.pivotaltracker.com/story/show/187609408

api: rename modified_by to updated_by in examples

---

docs/appnotes/0007-populating-source-metadata.md

This PR adds an application note about populating Source metadata from Flow metadata.
Story URL: https://www.pivotaltracker.com/story/show/187609488

appnote: add populating source metadata app note

---

docs/appnotes/0008-timestamps-in-TAMS.md

Add appnote 0008 covering various aspects of the use of timestamps in TAMS
Story URL: https://www.pivotaltracker.com/story/show/187624530

Add appnote 0008 on timestamps in TAMS

---

README.md
api/examples/service-get-200.json

Updates docs links to point at (upcoming) v5.0 release so the correct links get baked into the tag
Story URL: https://www.pivotaltracker.com/story/show/187772613
N/A

Update docs links to point to v5 release

---

api/TimeAddressableMediaStore.yaml

Add missing headers to HEAD requests
Story URL: https://www.pivotaltracker.com/story/show/188027994

Add missing headers to HEAD requests

---

api/TimeAddressableMediaStore.yaml

Fix tag deleted descriptions. Minor fix to punctuation consistency.
Story URL:

Fix tag deleted descriptions

---

docs/README.md
docs/appnotes/0003-tag-names.md
docs/appnotes/0011-c2pa.md

Add an application note detailing an approach for working with C2PA provenance data in TAMS Flows.
Story URL: N/A

Application note for working with C2PA provenance in TAMS

---

README.md
examples/.gitignore
examples/Makefile
examples/README.md
examples/client.py
examples/credentials.py
examples/hls_sample_content.sh
examples/ingest_hls.py
examples/outgest_file.py
examples/requirements.txt
examples/simple_edit.py

This PR adds some example Python code that demonstrates some uses of the TAMS API.
Story URL: https://www.pivotaltracker.com/story/show/188034316

Add some example python code that uses the TAMS API

---

examples/README.md

Remove some incorrectly copied text
Story URL:

Remove some copy-paste errors

---

api/schemas/flow-segment.json

Add assumed default to `sample_offset`
Story URL:

Add assumed default to `sample_offset`

---

.github/pull_request_template.md
docs/README.md
docs/adr/0025-flow-property-updates.md

This PR has various minor changes:
* Update PR template
* Fix a broken ADR link
* Update an ADRs status which was missed on original merge
Jira URL: https://jira.dev.bbc.co.uk/browse/CLOUDFIT-5376

Update PR template

---

api/TimeAddressableMediaStore.yaml

Add missing 403 on flow label PUT
Jira URL:

Add a missing 403

---

examples/simple_edit.py

Fixes a bug where interval edit mode only worked correctly when the specified TimeRange was at the start of a segment.
Jira URL: N/A - bug reported on Slack
Fixes a bug introduced in #108 

example: Fix bug in timeshift calc

---

examples/credentials.py

_Brief description of what this PR does._
Jira URL:

Add common scopes to example scripts

---

docs/adr/0031-flow-image-support.md

Mark ADR0031 as accepted
Jira URL: https://jira.dev.bbc.co.uk/browse/CLOUDFIT-3543

Mark ADR0031 as accepted

---

docs/README.md
docs/adr/0030-allow-external-media-objects.md

Mark ADR0030 accepted
Fix links
Jira URL:

Mark ADR0030 accepted

---

docs/README.md
docs/adr/0027-add-objects-api-endpoint.md
docs/adr/0028-authentication-methods.md

This PR fixes the following issues:
* ADR0027 was merged in https://github.com/bbc/tams/pull/111 and should have been marked as accepted.
* ADR0027 should have been added to the ADR list
* ADR0028 was merged in https://github.com/bbc/tams/pull/113 and should have been marked as accepted.
Jira URL:

Mark ADRs as accepted

---

api/TimeAddressableMediaStore.yaml

Add note that store implementations should verify that creation/modification of Flows will not conflict with Sources
Jira URL: https://jira.dev.bbc.co.uk/browse/CLOUDFIT-5456

Clarify behaviour on conflicting Flow/Source metadata
